### ISSUE TITLE
Add goals for this project to wiki

### ISSUE THREAD

**Issue by jcbhmr** [devcontainers-contrib/features#181]
It would probably be beneficial to add a `Goals.md` page to the Wiki which outlines the current scope and covered use-cases for this feature collection.

With recent discussion about "what is the scope of features in this repo?" and "what should be a feature?", I think it would be a good idea to consolidate these into a single document. **This shouldn't necessarily happen _now_** given that discussion is still ongoing, but it would be foolish to think that we all (@DaneWeber @danielbraun89 and @jcbhmr being primary discuss-ers) remember the gist of like 100+ comments over 10+ threads about goals and scope of this project.

Relevant discussions: #171 #173 #175 #172

## Tasks

- [ ] Add a `Goals.md` to the `wiki/` folder
- [ ] Answer "what is the goal of this repo?"
- [ ] Answer "what qualifies as a feature?"
- [ ] Link to relevant discussions for more details

_Should this file be called something else? Maybe folded into the `wiki/README.md` file?_

/assign @jcbhmr

**Comment by danielbraun89** [comment]
👍 
+ written some thoughts on gitter https://gitter.im/devcontainers-contrib/community?at=6391d87a8bdea01368a772eb

**Comment by jcbhmr** [comment]
Actually, I think this is a good opportunity to use GitHub's new Projects feature to organize "task" issues into a concrete "medium term" goal planner.

https://docs.github.com/en/issues/planning-and-tracking-with-projects/learning-about-projects/quickstart-for-projects

> So regarding goals, I think they should be something along the lines of
>
> Reduce effort to create features
> Increasing the quality of features
> Enabling more categories of features
> regarding goal 1, thats what the cookiecutter generator was originaly for, but now proven to be a. not flexible enough and b. only provide trivial features which are really no brainer) so probably will be replaced by some JS prompt generator?
>
> goal 2: Thats basically the common install.sh header and functions, which altho it certainly increase code quality- it also might increase the learning curve for new comers (a new concept to understand?)
>
> goal 3:
> So we have the feature dependency system path (discussed here https://github.com/devcontainers-contrib/features/discussions/171)
> This seems to me a one major gap that if filled will result in an ability to create much more complex features which are a composition of another features etc
>
> So far so good :) Problem is - I dont think I/we have the capacity to tackle al goals at once... I certainly dont have the time. So jcbhmr DaneWeber If you had to choose one to prioritize what should it be?

In regards to this comment, I largely agree with the overarching goals. I'd like to add some of my own concrete articulations of my own ideas:
1. Figure out a solution to re-using Bash functions.
5. Implement _that solution_.
6. Figure out a solution to using features that need another feature.
7. Implement _that solution_
8. Implement the shift to ecosystem-level features.
9. Add more documentation about how to create features.

Moving to ecosystem-level features also entails the possibility of deprecating `npm`-based and `pip`-based features, but that's post-doing-it thinking. See https://github.com/devcontainers-contrib/features/issues/172#issuecomment-1346517078

Regarding your \#1 idea in the quote ("Reduce effort to create features"), here's some ideas that @jcbhmr could do to improve the docs:
1. Create a guiding Bash or Deno or Python script that prompts the user to do things. I don't know how generalized the feature creation can be to put it in a guiding script though.
2. Create a walkthrough to create a feature for something like Deno or another "simple-ish" cURL-based installer.
